### ISSUE TITLE
Namespace confliction with org/contrib/org-toc.el

### ISSUE THREAD

**Issue by yoshinari-nomura** [snosov1/org-toc#7]
It might not be an issue, just FYI.

Original org-mode has contrib directory. Unfortunately, it has org-toc.el, which is conflicting with your package name.

After a while, I had happily removed contrib/org-toc.el, but it took some time to understand what was happened.  But I'm afraid this confliction might discourage many people to introduce your great package.

**Comment by iqbalansari** [comment]
Hi,

Thanks for this great package, works really well. But the readme proposed solution does not work well. I have installed `org-plus-contrib` from elpa as such `org-toc.el` from that package shadows `org-toc.el` from this package. As such `require`, `load` and friends load the `org-toc.el` from org-plus-contrib. I **hacked** around this in my emacs using complete path to `org-toc` in the autoload by doing something like the following

```
(let ((org-toc-elpa-dir (car (file-expand-wildcards (concat package-user-dir "/org-toc*")))))
       (autoload #'org-toc-enable (concat org-toc-elpa-dir "/org-toc.el")))
```  

That atleast fixes the immediate problem. You might want to fix this soon otherwise there will be regular conflicts between the two `org-toc.el`

**Comment by snosov1** [comment]
Hi! Thanks for sharing the concern. 

I'm having hard time thinking of what can be done about it, since I believe it's too late to change the name of the mode. 

But I think I could provide an alias to the mode name (something like `org-toc-2`), so that people facing the conflict would use it instead of `org-toc`. What do you think about?

**Comment by iqbalansari** [comment]
Actually I am not sure that `org-toc-2` is the best prefix but honestly, I also cannot think of a better prefix, something like `toc-org` might also work. Irrespective of the prefix you choose, you then redefine the user facing functions (`org-toc-enable` and `org-toc-insert-toc`) to issue a warning to the user using `warn` about obsolete function/variables and then call the appropriate function. I think that should be enough to make users aware of the change.

**Comment by snosov1** [comment]
Thanks!

I hear what you're saying, but your proposal seems too involved to me and, honestly, I don't think it's worth it. Pinging every user to make them aware of the potential problem they might face sometime doesn't sound right to me.

So, I simply added an `org-toc-2` alias and updated the documentation to use it. That way, the package will continue to work for the current users and future users will be advised to use the `org-toc-2` package to avoid potential problems. 

The solution is not very pretty, but I believe it's the least evil.

**Comment by iqbalansari** [comment]
I am not sure I liked the solution (since `autoload` would still no work), but no problem thanks for looking into this.

**Comment by snosov1** [comment]
:+1:

**Comment by iqbalansari** [comment]
It seems you forgot to add the `org-toc-2` file.

**Comment by snosov1** [comment]
That was part of the plan. `org-toc-2` feature is simply provided along with the `org-toc`. My understanding is that it should work as I described. Is there a problem with that?

**Comment by iqbalansari** [comment]
Yes `(require 'org-toc-2)` will by default look for a file with named `org-toc-2.elc` or `org-toc-2.el` unless you supply the file name to load the feature from (this won't work because the file in org-contrib overshadows the file from this package).

**Comment by snosov1** [comment]
That's right. I tested it incorrectly. Ok, that's not as easy as I thought. I'll have to think about it some more.

**Comment by LeoUfimtsev** [comment]
I'm a new user to emacs and I've now spent a good hour figuring out the conflict between org-toc and org-toc. I love both packages, but the conflict is frustrating. 

This is not very future proof imho. New users will keep bumping into the conflicts and it makes emacs more complex to use. Imho it would make sense to create a new repo like org-dync-toc  (because the other one is static) and just leave a note in the readme of this repo to advise users to migrate to the new repo. I think existing users would eventually migrate to the newer package.

Just my 50 cents.

**Comment by snosov1** [comment]
For everybody in the thread, I've just renamed the module to `toc-org`, so, please, update your configuration files. Sorry for any inconvenience.
